### ISSUE TITLE
Several issues with default parameters

### ISSUE THREAD

**Issue by martinverner** [BradAndersonJr/GuitarEngine#7]
Hi Brad,

I get several issues when creating a guitar using default values.

`Failed:
Traceback (most recent call last):
  File "C:/Users/.../Fusion 360 plugins/GuitarEngine-master-391276a/Guitar Engine [Beta].py", line 1583, in buildFretboard
    extentToEntity = adsk.fusion.ToEntityExtentDefinition.create(extrudeFeature.faces.item(0), True)
  File "C:\Users/...
<img width="1620" alt="GuitarPluginIssues" src="https://github.com/bradandersonjr/GuitarEngine/assets/5664423/31e76f68-ceb5-4f8d-ba42-556b2a5378a6">
<img width="1620" alt="GuitarPluginIssues" src="https://github.com/bradandersonjr/GuitarEngine/assets/5664423/3eca8c61-f440-42b7-aa65-56a1b8337244">
/AppData/Local/Autodesk/webdeploy/production/dbacedcc6dabacdc41406088a765962c5f1923ad/Api/Python/packages\adsk\fusion.py", line 9935, in item
    return _fusion.BRepFaces_item(self, index)
RuntimeError: 2 : InternalValidationError : faces.size() > index`

And 

`Failed:
Traceback (most recent call last):
  File "C:/Users/.../Fusion 360 plugins/GuitarEngine-master-391276a/Guitar Engine [Beta].py", line 1932, in buildPickups
    constraints.addMidPoint(bridgeLines.item(5).startSketchPoint, cavitybridgeLines.item(9))
  File "C:\Users/.../AppData/Local/Autodesk/webdeploy/production/dbacedcc6dabacdc41406088a765962c5f1923ad/Api/Python/packages\adsk\fusion.py", line 41855, in item
    return _fusion.SketchLines_item(self, index)
RuntimeError: 3 : Bad index parameter`

The end result looks like this:

<img width="1620" alt="GuitarPluginIssues" src="https://github.com/bradandersonjr/GuitarEngine/assets/5664423/2b81ce01-ca76-4c9d-a08e-7946a156b065">

Otherwise, really cool plugin and good videos on Youtube. Thank you very much!

Fusion 36 version 2.0.16490 x86_64

**Comment by martinverner** [comment]
If I uncheck "Create Fret Cuts" and select Humbucker for bridge pickup, it works. Of course, I do not get Fret Cuts.

**Comment by martinverner** [comment]
Changing line 1583 to this seems to fix the Fret cutting issue

`extentToEntity = adsk.fusion.ToEntityExtentDefinition.create(offSurf.faces.item(0), True)`
